### ISSUE TITLE
Plugin has been closed?

### ISSUE THREAD

**Issue by Weeb** [nicumicle/simple-jwt-login#51]
There is currently a message on the official WordPress page stating that this plugin is no longer available. How come?

![image](https://user-images.githubusercontent.com/3097098/191765833-112dd1ce-ec1b-49fe-acb3-c17f9e6b8c0e.png)

**Comment by nicumicle** [comment]
Simple JWT Login is running through a security report and it has been temporarily closed due to some vulnerabilities in the JWT library that we use. 

I'm working to fix this issue and by the end of the week, I will send the plugin to be reviewed.
After I send it to review, we will have to wait to be reapproved. 

Hopefully, in a couple of days, the plugin will be live on WordPress.org.

Meanwhile, you can download the plugin from GitHub. I will also include a download link on the https://simplejwtlogin.com website.

I will come back with updates.

**Comment by dani3l3** [comment]
Are our sites vulnerable to a specific attack, at this moment, or is it just "a" vulnerability in the library that can't be directly exploited? Do you know/have insights to share about the issue?
Thanks,

**Comment by nicumicle** [comment]
It is just a vulnerability in the library. The plugin is not affected by this.

The vulnerability refers to when decoding the JWT with multiple keys(array of keys), and the user changes the algorithm in the JWT header. 
The `simple-jwt-login` plugin allows only one algorithm to be specified, and only one "decryption key". 
So in simple words,**your sites are safe**. The plugin code never enters that part of the code in the library.

**Comment by nicumicle** [comment]
The plugin is now open. Version `3.4.7` has been released.
