### ISSUE TITLE
bug: Not working with woocommerce end point

### ISSUE THREAD

**Issue by ramdcet** [nicumicle/simple-jwt-login#78]
Hi,
I have successfully integrated it with login & register functonality. i want to use it with woocommerce endpoint, when i called the woocommerce end point then it showing error “{ “code”: “woocommerce_rest_cannot_view”, “message”: “Sorry, you cannot list resources.”, “data”: { “status”: 403 } }” . I have enabled the setting from  “All WordPress endpoints checks for JWT authentication”. I tried to pass the JWT Token as header/ as authorization but this is not working. Any hepl?

![image](https://user-images.githubusercontent.com/4659487/230889120-366e01c6-f164-4867-9cbd-d0bb28d1fbb4.png)
![image](https://user-images.githubusercontent.com/4659487/230889147-7dcf1c6e-f99d-4983-bdee-b2da13ae4427.png)
![Uploading image.png…]()

**Comment by nicumicle** [comment]
Hi @ramdcet,

I just tried it on my side, and all seems to work.

## JWT query parameters
![Screenshot from 2023-04-15 07-40-42](https://user-images.githubusercontent.com/20170987/232186900-981639da-64b0-47ad-a6ad-e6ee2d9880b6.png)

## JWT headers
![Screenshot from 2023-04-15 07-42-32](https://user-images.githubusercontent.com/20170987/232186926-9021ba38-f8ca-4c30-bab3-39d02fd074d5.png)

## JWT Authorization
![Screenshot from 2023-04-15 07-44-14](https://user-images.githubusercontent.com/20170987/232186937-a655aea4-6e96-45c5-8e60-d48273da374e.png)

Have you been able to call other endpoints?
For example, 
```
http://{{HOST}}/?rest_route=/wp/v2/posts&JWT={JWT}
```
One common problem might be that the `Authorization` header might be missing when you make the request.

## Possible Fix 1
So, please make sure that you have the following in your .htaccess file:
```
RewriteEngine On
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

## Possible Fix 2
Another simple way would be to change the header name for "Authorization" to something else in the simple-jwt-login plugin settings (General -> Get JWT token from -> Header). For example, you can try "Auth".
![image](https://user-images.githubusercontent.com/20170987/232187327-f1c43052-ba12-40af-94e8-cd538c1b8293.png)
 After that, please make a request with the "Auth" header instead of "Authorization".


Let me know if it works after you try these examples.

Best regards,
Nicu.

**Comment by ramdcet** [comment]
Thanks for update

**Comment by nicumicle** [comment]
@ramdcet, is this issue resolved for you?

**Comment by sianami123** [comment]
![Image](https://github.com/user-attachments/assets/44b42662-3cd2-448c-bcb3-146651ef2c5a)

![Image](https://github.com/user-attachments/assets/cd26c827-bb57-422c-a04f-413b3340d53f)

![Image](https://github.com/user-attachments/assets/078acc33-45b1-4267-9284-08eea45aa0ba)
i have same issue on /wc/ (/wp/ endpoints works)
i edited htaccess and changed Authorization to Auth in header
any solution?how fixed? @ramdcet
